### PR TITLE
gadgets: seccomp: Include seccompprofile from v1beta1.

### LINKED ISSUE #407: [FIX] Update `seccomppprofile` operator
## Description

Seccomp profile was update from `v1alpha1` to `v1beta1` in kubernetes-sigs/security-profiles-operator#674.

## Impact

Our `seccompd-advisor` gadget does not work anymore.

## Environment and steps to reproduce

You first need to setup a `minikube` environment, then you can run the following:

```bash
kubectl apply -f docs/examples/seccomp/basic.yaml
kubectl apply -f docs/examples/seccomp/unconfined.yaml
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.0/cert-manager.yaml
kubectl --namespace cert-manager wait --for condition=ready pod -l app.kubernetes.io/instance=cert-manager
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/master/deploy/operator.yaml
kubectl wait --for condition=ready -n seccomp-demo pod hello-python
perl -pi -e 's/demo-node/minikube/' docs/examples/seccomp/trace-external.yaml
kubectl apply -f docs/examples/seccomp/trace-external.yaml
kubectl annotate -n gadget trace/seccomp gadget.kinvolk.io/operation=start
sleep 10
kubectl annotate -n gadget --overwrite trace/seccomp gadget.kinvolk.io/operation=generate
kubectl get seccompprofile -A
NAMESPACE                    NAME                 STATUS   AGE
# No hello-python profile!!!
security-profiles-operator   log-enricher-trace            77s
security-profiles-operator   nginx-1.19.1                  76s
kubectl describe trace -n gadget seccomp | grep "Operation Error"
Operation Error:  Failed to update resource: no matches for kind "SeccompProfile" in version "security-profiles-operator.x-k8s.io/v1alpha1"
```

## Expected behavior

Trace Operation Error should be empty and Seccomp profile should be generated.

## Additional information

There is no new release with this change.

### PR DESCRIPTION
**Pull request by eiffel-fl**
Hi.

This PR fixes #407, for this it does principally three things:
1. Replaces `seccompprofile/v1alpha1` by `seccompprofile/v1beta1`.
2. Bumps `k8s.io/cli-runtime` to v0.21.0 to avoid compilation error.
3. Fixes a compilation error when an argument was passed by pointer.

The previously failing test now passes:

```bash
kubectl apply -f docs/examples/seccomp/basic.yaml
kubectl apply -f docs/examples/seccomp/unconfined.yaml
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.0/cert-manager.yaml
kubectl --namespace cert-manager wait --for condition=ready pod -l app.kubernetes.io/instance=cert-manager
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/master/deploy/operator.yaml
kubectl wait --for condition=ready -n seccomp-demo pod hello-python
perl -pi -e 's/demo-node/minikube/' docs/examples/seccomp/trace-external.yaml
kubectl apply -f docs/examples/seccomp/trace-external.yaml
kubectl annotate -n gadget trace/seccomp gadget.kinvolk.io/operation=start
sleep 10
kubectl annotate -n gadget --overwrite trace/seccomp gadget.kinvolk.io/operation=generate
kubectl get seccompprofile -A
NAMESPACE                    NAME                 STATUS   AGE
# hello-python profile is present!
seccomp-demo                 hello-profile                 50s
security-profiles-operator   log-enricher-trace            4m57s
security-profiles-operator   nginx-1.19.1                  4m56s
kubectl describe seccompprofile -n  seccomp-demo hello-profile
Name:         hello-profile
Namespace:    seccomp-demo
Labels:       <none>
Annotations:  seccomp.gadget.kinvolk.io/container: hello-python
              seccomp.gadget.kinvolk.io/node: minikube
              seccomp.gadget.kinvolk.io/pod: seccomp-demo/hello-python
              seccomp.gadget.kinvolk.io/trace: gadget/seccomp
API Version:  security-profiles-operator.x-k8s.io/v1beta1
Kind:         SeccompProfile
...
      wait4
      write
      writev
Events:  <none>
```

Best regards.

### CODE REVIEW

**Comment by eiffel-fl** [comment]
Seccomp operator developpers released [v0.4.0](https://github.com/kubernetes-sigs/security-profiles-operator/releases/tag/v0.4.0).
I updated this PR to reflect this change.

**Review by alban — COMMENTED** [review]
Thanks! I think this PR should be completed. Some changes to do:
- Fix conflicts and rebase
- Some unrelated changes in object files (example: `dns.o` etc.) to remove

Otherwise, the code looks good to me.

**Comment by eiffel-fl** [comment]
Hi.

Thank you for your feedback!
Actually, I do not really know what to do with this contribution. Should we merge it right now? Or better to wait `seccompprofile` to become stable and update it once it is stable?

Best regards.

**Comment by eiffel-fl** [comment]
Hi.

I rebased it and removed the `*.o`.

Best regards.

**Comment by eiffel-fl** [comment]
Thank you for the review!

**Pull request merged**
