### PR TITLE
capabilities: add --unique flag

### PR DESCRIPTION
**Pull request by alban**
# capabilities: add --unique flag

On some workloads, the capabilities trace gadget has a lot of repeated output and it makes the gadget not easily usable.

There was already some BPF code to implement uniqueness with pid or cgroup but it was not plugged to the CLI. This patch reuses the 'seen' map that implemented the uniqueness logic but using the mntns id instead.

## How to use

Just add `--unique`.

## Testing done

Tested with and without the `--unique` flag by deploying Tracee on Kubernetes with Helm following its [documentation](https://github.com/aquasecurity/tracee/blob/main/docs/installing/kubernetes.md):

```
$ kubectl gadget trace capabilities -n tracee-system -o custom-columns=pod,comm,capname,verdict --unique
POD                              COMM              CAPNAME               VERDICT
tracee-dmjsc                     tracee-ebpf       CAP_SETPCAP           Allow  
tracee-dmjsc                     tracee-ebpf       CAP_SYS_PTRACE        Deny   
tracee-dmjsc                     tracee-ebpf       CAP_SYS_ADMIN         Allow  
tracee-dmjsc                     tracee-ebpf       CAP_SYS_RESOURCE      Allow  
tracee-posteeui-85468f4598-cbxr5 chown             CAP_DAC_READ_SEARCH   Deny   
tracee-posteeui-85468f4598-cbxr5 chown             CAP_DAC_OVERRIDE      Allow  
tracee-posteeui-85468f4598-cbxr5 chown             CAP_CHOWN             Allow  
tracee-postee-0                  chown             CAP_DAC_READ_SEARCH   Deny   
tracee-postee-0                  chown             CAP_DAC_OVERRIDE      Allow  
tracee-postee-0                  chown             CAP_CHOWN             Allow  
tracee-posteeui-85468f4598-cbxr5 runc:[2:INIT]     CAP_FOWNER            Allow  
tracee-postee-0                  runc:[2:INIT]     CAP_FOWNER            Allow
```

Tested with local-gadget:
```
$ sudo ./local-gadget trace capabilities --unique -r docker
CONTAINER                                           PID        COMM             UID        CAP CAPNAME                            AUDIT                VERDICT
elegant_shirley                                     537456     chown            0          0   CAP_CHOWN                          1                    Allow  
```
While running:
```
$ docker run -ti --rm busybox
/ # chown 1000:1000 /usr
/ # chown 1000:1000 /usr
/ # chown 1000:1000 /usr
/ # chown 1000:1000 /usr
```

### CODE REVIEW

**Comment by alban** [comment]
Thanks! Patch & PR description updated. It works with local-gadget too.

**Review by mauriciovasquezbernal — APPROVED** [review]
I tested and it works fine!

**Comment by mauriciovasquezbernal** [comment]
btw, I implemented some unit tests for this feature in https://github.com/kinvolk/inspektor-gadget/commits/mauricio/test-capable-unique, I'll open a PR once it's merged.

**Comment by alban** [comment]
> I am just thinking to this, but do you plan to give back the `Verdict` feature to `iovisor/bcc`?
> I think it would be cool if the C version of this tool has this feature too!

I didn't plan to do it. It seems to be a good idea to me. Feel free to do it.

**Pull request merged**
