### PR TITLE
integration: Fix cleaning up commands

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
t.Fatal() is called when a test fails, it ends up calling runtime.Goexit()
to exit the current goroutime.

The Goexit documentation states that:

'''
Goexit terminates the goroutine that calls it. No other goroutine is affected.
Goexit runs all deferred calls before terminating the goroutine. Because Goexit
is not a panic, any recover calls in those deferred functions will return nil.
'''

The previous logic was using the same defer call to run the tests and
perform the cleanup, if a test failed then that function was interrupted
without doing the cleanup.

This commit uses a different defer call to perform the cleanup,
guaranteeing that it's always done.

---

An example of this failing can be found at https://github.com/kinvolk/inspektor-gadget/actions/runs/1684275158, `TestOpensnoop` failed and then `TestProfile` failed with `pods "test-pod" already exists` because the cleanup wasn't done properly.

### CODE REVIEW

**Comment by eiffel-fl** [comment]
Thank you for this one!
But I am working on the CI now in #469 (this is still WIP, I need to polish it) and I added [`-test.failfast`](https://github.com/kinvolk/inspektor-gadget/pull/469/commits/42a5a999499ee3a7ee1a13066afebd10503d7a33#diff-bfa9217ac9c99d9d12382126766604229958cbcfd97742e9870f8807f58083efR19) to fail the whole integration test if one sub-test fails.
Do these two solutions overlap or complete each other?

**Review by eiffel-fl — COMMENTED** [review]
Thank you for this one!
But I am working on the CI now in #469 (this is still WIP, I need to polish it) and I added [`-test.failfast`](https://github.com/kinvolk/inspektor-gadget/pull/469/commits/42a5a999499ee3a7ee1a13066afebd10503d7a33#diff-bfa9217ac9c99d9d12382126766604229958cbcfd97742e9870f8807f58083efR19) to fail the whole integration test if one sub-test fails.
Do these two solutions overlap or complete each other?

**Comment by mauriciovasquezbernal** [comment]
Those are independent. This one here is a bug.

**Review by eiffel-fl — APPROVED** [review]
I understand more the problem, thank you for your precision and this contribution! It is appreciated.
Can you please add the following to your commit message:

```
Fixes: f6e6fdfd18e8 ("integration: Add start() and stop().")
```

**Pull request merged**
