### PR TITLE
change maximum entries for mntns_set and default values

### PR DESCRIPTION
**Pull request by ogozman**
This change is done for the maps to be compatible with tracee maps

mntns_set maxentries change from 128 to 10240 
default values are set to 1 so that filtter in tracee would work

# Testing done

Tested with with local deployment

### CODE REVIEW

**Review by alban — APPROVED** [review]
LGTM

**Review by mauriciovasquezbernal — APPROVED** [review]
Looks good!

**Comment by alban** [comment]
By the way, in bcc the maximum entries for mntns_set is 1024:

https://github.com/iovisor/bcc/blob/3318c261a9e6ef82484fc0f5f5254599b191b289/src/python/bcc/containers.py#L58
```
    BPF_TABLE_PINNED("hash", u64, u32, mount_ns_set, 1024, "MOUNT_NS_PATH");
```

Does that mean that for bcc it does not matter if the pinned map has a different max_entries, whereas it matters for libbpf?

**Comment by mauriciovasquezbernal** [comment]
> Does that mean that for bcc it does not matter if the pinned map has a different max_entries, whereas it matters for libbpf?

I think that's correct. According to my understanding from https://github.com/iovisor/bcc/blob/3318c261a9e6ef82484fc0f5f5254599b191b289/src/cc/bpf_module.cc#L321 BCC doesn't those checks. I'm not sure what guarantees that the maps are compatible, perhaps it's up to the verifier.

**Pull request merged**
