### PR TITLE
pkg/gadgettracermanager: remove bpf file and assets

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
The gadget tracer manager creates (and pins) an eBPF map that is used
by the gadget to filter the events of the different containers.

Before this commit the maps were defined in a .c file that was compiled
with clang/llvm into a .o file, then that file was embedded into a
.go file by using go-bindata. This process is so complex and not needed
because those maps can be created (and pinned) just performing some
system calls.

This commit uses the cilium/ebpf library to perform that task.

### CODE REVIEW

**Comment by alban** [comment]
Thanks! It simplifies the code.

I had a look at `git grep gobpf` and there are still some mentions:
* go.mod, go.sum: is it still required because of indirect dependencies or can it be removed?
* README.md: we can keep the mention because of the network policy advisor but we could add a mention of cilium/ebpf too
* entrypoint.sh, bcc-wrapper.sh: related to traceloop and the network policy advisor, so I guess that does not change for now

This PR switches from gobpf to cilium/ebpf; there is another PR (seccomp PR: https://github.com/kinvolk/inspektor-gadget/pull/156) switching from gobpf to tracee/libbpfgo. I think the gadget tracer manager should use only one Go BPF library. Hopefully the seccomp advisor can be reimplemented with cilium/ebpf. The tracepoint/kprobe support in cilium/ebpf improved a lot so I think it should be possible. I suggest to review & merge this PR first and fix the seccomp PR after.

**Comment by alban** [comment]
The generated file pkg/gadgettracermanager/tracer-map-assets-bpf.go should be removed from git too.

**Comment by mauriciovasquezbernal** [comment]
>     * go.mod, go.sum: is it still required because of indirect dependencies or can it be removed?

It's still required after running `go mod tidy`. It's a indirect dependency from `github.com/kinvolk/traceloop/pkg/tracemeta`.

>     * README.md: we can keep the mention because of the network policy advisor but we could add a mention of cilium/ebpf too

Added a mention. 

> 
>     * entrypoint.sh, bcc-wrapper.sh: related to traceloop and the network policy advisor, so I guess that does not change for now

Yes, those comments are relevant for those two.  


> I think the gadget tracer manager should use only one Go BPF library. 

I agree. Actually no only the gadget tracer manager but it would be great if we converge to a single library for Inspektor Gadget. 

> Hopefully the seccomp advisor can be reimplemented with cilium/ebpf. The tracepoint/kprobe support in cilium/ebpf improved a lot so I think it should be possible. 

Yes. Perhaps we can do the same some day for traceloop :thinking: 

> I suggest to review & merge this PR first and fix the seccomp PR after.

Makes sense to me. 

Thanks for the review.

**Review by alban — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
