### PR TITLE
Add "profile" gadget

### PR DESCRIPTION
**Pull request by alban**
Based on BCC's tool profile:
https://github.com/iovisor/bcc/blob/master/tools/profile_example.txt

---

TODO:
- [x] https://github.com/iovisor/bcc/pull/2824

### CODE REVIEW

**Comment by mauriciovasquezbernal** [comment]
How is it supposed to work?

I see nothing in the output
```
mvb@asus ~/.../inspektor-gadget $ ./inspektor-gadget profile
Node numbers: 0 = ip-10-0-13-205 1 = ip-10-0-25-233
```

**Comment by alban** [comment]
You should select pods with `--label` or similar. Also, if the selected pods don't take much CPU, it is possible that the samples don't pick anything. Might work better if the processes are actively using the CPU. This is a WIP so I have not tested it properly.

**Comment by mauriciovasquezbernal** [comment]
I tested it and I'm able to see the output in folded mode, is there a specific reason to use that format?

I added some more documentation in https://github.com/kinvolk/inspektor-gadget/pull/47.

I think it'd be good to remove the deployment options and other non related things from this PR so we can merge it until we make a decision on the other changes.

**Comment by alban** [comment]
> I tested it and I'm able to see the output in folded mode, is there a specific reason to use that format?

I liked the short form but maybe it needs to be optional like in the bcc tool upstream...

> I think it'd be good to remove the deployment options and other non related things from this PR so we can merge it until we make a decision on the other changes.

It makes sense. It can be rebased on master now.

**Pull request merged**
