### PR TITLE
gadget.Dockerfile: mitigate K8s bug with existing manifests

### LINKED ISSUE #433: Remove /var/run symlink from container image to mitigate Kubernetes bug
## Description

Right now IG container image has a `/var/run` symlink pointing to `/run`, which with currently used deployment manifests makes it hit this Kubernetes bug, which may lead to node CPU exhausion: https://github.com/kubernetes/kubernetes/issues/106962.

## Impact

If IG crashes on the node, it may make node become unavailable.

## Additional information

Adding `RUN rm /var/run` to Dockerfile should be sufficient to address this and mitigate the issue.

### PR DESCRIPTION
**Pull request by invidian**
Closes #433

Signed-off-by: Mateusz Gozdek <mgozdek@microsoft.com>

### CODE REVIEW

**Comment by mauriciovasquezbernal** [comment]
This sym link comes from the ubuntu image we use as a base:

```
$ docker run ubuntu:20.04 ls -la /var/run
lrwxrwxrwx 1 root root 4 Aug 27 07:16 /var/run -> /run
```

This PR LGTM but I asked a review from @alban.

**Comment by alban** [comment]
In pkg/gadgettracermanager/containerutils/ we define DEFAULT_SOCKET_PATH for each supported CRI:
```
DEFAULT_SOCKET_PATH = "/run/containerd/containerd.sock"
DEFAULT_SOCKET_PATH = "/run/crio/crio.sock"
DEFAULT_SOCKET_PATH = "/var/run/docker.sock"
```

The gadget pod has a bind mount from host path /run to /run. With this patch, /var/run will not longer point to the host volume /run. So I expect gadget will no longer be able to connect to Docker. This only affects Kubernetes setups using Docker. Kubernetes setups using containerd or cri-o uses a socket path without the /var/run. This is used to get the pids of containers that are already running when gadget starts.

So I think we'll need the following (untested!):
```diff
-DEFAULT_SOCKET_PATH = "/var/run/docker.sock"
+DEFAULT_SOCKET_PATH = "/run/docker.sock"
```

**Comment by invidian** [comment]
I wonder if changing the default path won't break anything. Perhaps there is some other workaround which could be done :thinking:

**Comment by mauriciovasquezbernal** [comment]
> But are we moutning /var/run into the container even?

No, we are not. I think we should also mount it, otherwise if docker is running in a host where `/var/run` and `/run` are different folders then Inspektor Gadget won't be able to contact it from the container. 

Another possibility is to define those paths and append `/host` to all of them before, anyway we're mounting the full host file system into /host for the container.

**Comment by invidian** [comment]
```
DEFAULT_SOCKET_PATH = "/run/containerd/containerd.sock"
DEFAULT_SOCKET_PATH = "/run/crio/crio.sock"
DEFAULT_SOCKET_PATH = "/var/run/docker.sock"
```

Considering the following, I think changing `/var/run/docker.sock` to `/run/docker.sock` will make it consistent with other runtimes, so I'm all for it. You may consider it a breaking change, just to be safe.

>Another possibility is to define those paths and prepend /host to all of them, anyway we're mounting the full host file system into /host for the container.

I think having those paths configurable and using `/host` as a prefix in the container is a good thing to do regardless. I'll open an issue for it.

**Comment by invidian** [comment]
I pushed the change of default path and opened bunch of new issues to address mentioned concerns/suggestions.

**Comment by mauriciovasquezbernal** [comment]
I tested it and the IG is able to contact docker from the container so it's fine. Thanks!

**Review by mauriciovasquezbernal — APPROVED** [review]

**Pull request merged**
