### PR TITLE
Add OSX builds

### PR DESCRIPTION
**Pull request by alban**
Fixes https://github.com/kinvolk/inspektor-gadget/issues/65

### CODE REVIEW

**Comment by fredleger** [comment]
Hi @alban 

I tried it and the make operation failled with the following logs:

**Comment by mauriciovasquezbernal** [comment]
Hi @fredleger, 

According to your output, you are trying to build the Inspektor Gadget container image, to generate only the executable you run in your machine, you can use `make kubectl-gadget-darwin-amd64`. Please let me know if this works for you.

**Comment by alban** [comment]
Maybe we could get `make -C gadget-container build` to run in docker containers, so that it would also be possible to build the "gadget" container image on OSX. I don't know how that works.

@fredleger could you also try to download the build artifact from this PR (https://github.com/kinvolk/inspektor-gadget/pull/73/checks) to check if the binary works on OSX?

**Comment by fredleger** [comment]
Hello,

The build itself seems to be working (i don't have a Gadget daemon or pod running so i should test further).

2 things though:
* The binary is unsigned which oblige to "hack" the osx security prefs. but i guess you can live with it
* in my experience if you want to distribute it as a plugin integrating it in krew is a simple and good choice : https://github.com/kubernetes-sigs/krew

Thanks for building this i will give it a deeper try starting from now

**Comment by alban** [comment]
@fredleger  thanks for testing. 
@mauriciovasquezbernal ok for merging?
I think the issue with `make -C gadget-container build` on osx could be done later, at least the next release would have a binary for osx.
I agree about krew, there is an issue about it: https://github.com/kinvolk/inspektor-gadget/issues/30

**Pull request merged**
